apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chp7-daemonset-demo
  labels:
    k8s-class: chp7-daemonset-demo
spec:
  selector:
    matchLabels:
      name: chp7-daemonset-demo
  template:
    metadata:
      labels:
        name: chp7-daemonset-demo
    spec:
      # tolerations:
      # # this toleration is to have the daemonset runnable on master nodes
      # # remove it if your masters can't run pods
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      containers:
      - name: chp7-ds-master-busybox
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]